events {}

http {

    server {
        listen 80;
        server_name libraryweb.duckdns.org;

        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name libraryweb.duckdns.org;

        ssl_certificate     /etc/letsencrypt/live/libraryweb.duckdns.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/libraryweb.duckdns.org/privkey.pem;

        # Redirect the root URL to your homepage
        location = / {
            return 302 /library_management/Homepage.html;
        }

        location /library_management/ {
            proxy_pass http://library-app:8080;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
